---
apiVersion: v1
kind: Namespace
metadata:
  name: game-hub
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: game-hub
  name: deployment-game-hub
spec:
  replicas: 5
  selector:
    matchLabels:
      app.kubernetes.io/name: game-hub
  template:
    metadata:
      labels:
        app.kubernetes.io/name: game-hub
    spec:
      containers:
      - name: game-hub
        image: public.ecr.aws/l6m2t8p7/docker-2048:latest  # replace with your Flask image
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        
        # ---------------------------
        # HEALTH CHECKS (VERY IMPORTANT)
        # ---------------------------
        readinessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5

        livenessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 10

        # ---------------------------
        # CLOUDWATCH LOGGING VARIABLES
        # ---------------------------
        env:
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: AWS_REGION
          value: "us-east-1"   
        - name: CW_LOG_GROUP
          value: "/eks/game-hub"
        - name: CW_LOG_STREAM
          value: "flask-game"

        resources:
          requests:
            cpu: "50m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  namespace: game-hub
